apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: personapp
  name: personapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personapp
  template:
    metadata:
      labels:
        app: personapp
    spec:
      containers:
      - image: ubuntu
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        name: personapp
        env:
        - name: spring.profiles.active
          value: "dev"                       
---
apiVersion: v1
kind: Service
metadata:
  name: personapp-service
spec:
  selector:
    app: personapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003  





                 

